# Generated by Django 3.0.4 on 2020-05-22 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(blank=True, max_length=3)),
                ('cidade_desaparecimento', models.CharField(max_length=50)),
                ('estado_desaparecimento', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Perdido'), (2, 'Comunicado'), (3, 'Encontrado')], default=1)),
                ('informacoes_extras', models.CharField(blank=True, max_length=250)),
                ('dono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
