# Generated by Django 3.0.4 on 2020-05-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200523_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='informacoes_extras',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
