# Generated by Django 3.0.6 on 2020-05-24 13:42

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200523_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(upload_to=main.models.UploadToPathAndRename('2020_05_24_')),
        ),
    ]
